### ISSUE TITLE
Bug: The word "Anything" shows under the "Random Gen." button

### ISSUE THREAD

**Issue by Shuggaloaf** [adougherty/random-everything-generator#4]
I lied to you on Reddit. I said I'd only have a suggestion for you and here's a bug. :-)

Since a pic is worth 1000 words: 
<img src="https://user-images.githubusercontent.com/79543184/146300057-8b313b33-afb8-4669-b724-ce999f4fea45.png" width="35%" />

I'm thinking you might know about this already because when I take a look at your screenshot, I can see it there as well. Have to zoom in real close and look very hard but it's there, behind the search bar.

**Comment by adougherty** [comment]
Thank you! This will be fixed in the next release
